service: alarm-web

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  environment:
    FROM_EMAIL_ADDRESS: ${file(variables.yml):environment.FROM_EMAIL_ADDRESS}
    TO_EMAIL_ADDRESS: ${file(variables.yml):environment.TO_EMAIL_ADDRESS}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "ses:SendEmail"
         - "ses:SendRawEmail"
       Resource: "*"


functions:
  detect:
    handler: handler.detect
    events:
      - http:
          path: sensor/detect
          method: post
